#!/bin/bash
USAGE='Usage: scan.sh'
trap 'echo "$USAGE"; exit 1' ERR

DEVICE=${DEVICE:-wlan0}
ip link set $DEVICE down
iw dev $DEVICE set type managed
ip link set $DEVICE up
iw dev $DEVICE scan 2>&1 | grep $'^BSS\|^\tsignal\|^\tSSID\|channel [0-9]\+' | less
